input {
    kb_layout = hu
    numlock_by_default = true
    follow_mouse = 2

    touchpad {
        natural_scroll = yes
        tap-to-click = yes
        disable_while_typing = yes
    }

    sensitivity = 0
}